# Loading Librairies

import sys
import subprocess
from snakemake.utils import min_version
import os


from lib.scripts.FileManagement import FileManagement


# Workflow works only from Snkamake 6.0 version

min_version("6.0")


# Defining variables to use in the workflow


DATASET = "" # (data/ATAC-Seq)/"Dataset"
INPUTDATASET = ""
DATATYPE = ['Control', 'BA'] # (data/ATAC-Seq/Fastq/Dataset)/"Condition1", "Condition2"
DatasetCtrlAbrevInFile = "Ctrl"
threadsNumber = workflow.cores
OSComputer = 'Linux'
#condaEnvironment = "../../CondaEnvironment/{}/ChIPAnalysis.yml".format(OSComputer)
CondaEnvPathName = "/media/sheikhhpc/58bd26c7-a7e6-47a0-8bbc-524b51ca4a32/micromamba/envs/ATACSeqEnv"
condaEnvironment = "ATACSeqMambaEnv.yml"
referenceGenome = "../../data/ATAC-Seq/GenomeFasta/MusMusculusGenome.fa"
genomeIndexFolder = "../../data/ATAC-Seq/GenomeIndexFolder/MusMusculus"
bedGenesFiles='../../data/ATAC-Seq/BEDFile/Mus_musculus.GRCm38.100.bed'
peaksCallingType = 'None'
PairedEnd = True
scriptPath = "lib/scripts"
customBarcodeFile= ""
organism="mm"
typeheatmap = "TSS"
cpusPerTasks = 6

# Computing the FileManagement object to handle with files

fileManagement = FileManagement(dataset = DATASET, datasetype = DATATYPE, 
    inputpath = '../../data/ATAC-Seq/Fastq/', 
    outputpath = '../../output/ATAC-Seq/', 
    pairedend=PairedEnd)



# Listing all the files and dataset types

SAMPLESFILES = fileManagement.returninglistofsamples()
FASTQSAMPLESFOLDERS = fileManagement.returninputfolders()
OUTPUTFOLDERS = fileManagement.returningoutputfolders()

# For paired end files 

pairedEndFoldersBasenames = fileManagement.returnlistofsampleswthoutpe()
OUTPUTFOLDERSPELENGTH = fileManagement.returningpairedendlengthoutputfolders()

# If data are paired end data pairedEndFoldersBasenames is used
# else it is OUTPUTFOLDERS which are used to compute
# destination filenames and foldernames  

if PairedEnd:
    outputFolderNames = OUTPUTFOLDERSPELENGTH
    outputFolderBasenameNames = pairedEndFoldersBasenames

else:
    outputFolderNames = OUTPUTFOLDERS
    outputFolderBasenameNames = SAMPLESFILES

# Creating the folders for the main steps of the workflow
# These folders are always created even if the workflow 
# is used to process input raw data


FASTQCFolders = ["{pathway}/FastQC/{sample}".format(
    pathway = pathway, sample = sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]


if PairedEnd:
    newFASTQCFolders = []

    for folder in FASTQCFolders:
        newFASTQCFolders.append(folder)
        newFASTQCFolders.append(folder)

    FASTQCFolders = newFASTQCFolders
    del(newFASTQCFolders)


TrimGalorePaths = ["{pathway}/Trimming/{sample}".format(
    pathway = pathway, sample = sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

MappingFolders = ["{pathway}/Mapping/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

MAPQFolders = ["{pathway}/MAPQ/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

samStatMappingFolders = ["{pathway}/SamStatsMapping/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

samStatMAPQFolders = ["{pathway}/SamStatsMAPQ/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

samStatsPCRDuplicatesRemoveFolders = ["{pathway}/SamStatsPCRDuplicates/{sample}".format(
    pathway=pathway, sample=sample) for pathway, sample in\
    zip(outputFolderNames, outputFolderBasenameNames)]

PCRDuplicatesRemovedFolders = ["{pathway}/NoDup/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

QualControlFolder = ["{pathway}/QualControlMetricsFiles/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

bigWigFolders = ["{pathway}/bigWig/{sample}".format(
    pathway=pathway, sample=sample)\
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

BigWigMergeFolders = ['../../output/ATAC-Seq/{datasetType}/BigWigMerge/{dataType}'.format(
    datasetType=DATASET, dataType=dataType) for dataType in DATATYPE]

bamFilesMergedFolders = ['../../output/ATAC-Seq/{datasetType}/BamFilesMerged/{dataType}'.format(
    datasetType=DATASET, dataType=dataType) for dataType in DATATYPE]

BigWigComapreFolder = '../../output/ATAC-Seq/{datasetType}/BigWigCompare'.format(
    datasetType=DATASET)

multiBamSummaryFolder = '../../output/ATAC-Seq/{datasetType}/MultiBamFolder'.format(
    datasetType=DATASET)

correlationBamPlotFolder = '../../output/ATAC-Seq/{datasetType}/CorrelationBamPlot'.format(
    datasetType=DATASET)



listOfFoldersToCreate = [FASTQCFolders, 
    TrimGalorePaths, MappingFolders, 
    MAPQFolders, samStatMappingFolders, 
    samStatMAPQFolders, samStatsPCRDuplicatesRemoveFolders, 
    PCRDuplicatesRemovedFolders, QualControlFolder, bigWigFolders, 
    BigWigMergeFolders, bamFilesMergedFolders, 
    multiBamSummaryFolder, correlationBamPlotFolder]




# If dataset is different from the input dataset 


StrandCorrelationFolders = ["{pathway}/StrandCorrelations/{sample}".format(pathway=pathway, sample=sample) 
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)]

fingerprintsPlotsFolders = "../../output/ATAC-Seq/{dataset}/Fingerprints".format(
    dataset=DATASET)
        
CoverageMatrixFolders = ['../../output/ATAC-Seq/{datasetType}/CoverageMatrixFiles/{dataType}'.format(
    datasetType=DATASET, dataType=dataType) for dataType in DATATYPE]

BedFilesFolders = '../../output/ATAC-Seq/{datasetType}/BedFiles/{peaksCallingType}'.format(
    datasetType=DATASET, peaksCallingType=peaksCallingType)


    
PeaksCallingTuple = fileManagement.creatingpeakscallingfolders(ctrlcondition=DatasetCtrlAbrevInFile, 
    files=outputFolderBasenameNames, peakscallingtype=peaksCallingType)
        
PeaksCallingFoldersBasenames = PeaksCallingTuple[0]
AssembledFilesPeaksCalling = PeaksCallingTuple[1]

   
    
PeaksCallingFolders = ['../../output/ATAC-Seq/{datasetType}/PeaksCalling/{peaksCallingType}/{sample}'.format(datasetType=DATASET, 
    peaksCallingType=peaksCallingType, sample=sample) for sample in PeaksCallingFoldersBasenames]

SafFolder = '../../output/ATAC-Seq/{datasetType}/FRIPScore/{peaksCallingType}'.format(
    datasetType=DATASET, peaksCallingType=peaksCallingType)

FripFolders = ['../../output/ATAC-Seq/{datasetType}/FRIPScore/{peaksCallingType}/{sample}'.format(datasetType=DATASET, 
    peaksCallingType=peaksCallingType, sample=sample) for sample in PeaksCallingFoldersBasenames] 



# Extending the list of folders with the new ones

listOfFoldersToCreate.extend([fingerprintsPlotsFolders, 
    StrandCorrelationFolders, PeaksCallingFolders, SafFolder, 
    FripFolders, BedFilesFolders, CoverageMatrixFolders])






# Creating selected folders according data 


for directory in listOfFoldersToCreate:
    if type(directory) is list:
        for directoryInList in directory:
            shell("mkdir -p {folder}".format(folder=directoryInList))
    else:
        shell("mkdir -p {folder}".format(folder=directory))




# Creating necessary output for the all rule 


HTMLReportFASTQCBefTrimming = ["{pathway}/{sample}_fastqc.html".format(
    pathway=pathway, sample=sample) for pathway, sample in zip(FASTQCFolders, SAMPLESFILES)]


FASTQsamplesAfterTrimming = ["{samples}".format(samples=samples) 
    for samples in fileManagement.returningtrimmingsamples()]


samFilesMapping = ["{pathway}/{sample}.sam".format(pathway = pathway, 
            sample=sample) for pathway, sample in zip(MappingFolders, 
            outputFolderBasenameNames)]


samStatReportFilesMapping = ["{pathway}/{sample}.samStatsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        samStatMappingFolders, outputFolderBasenameNames)] 


samFlagReportFilesMapping = ["{pathway}/{sample}.samFlagsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in 
    zip(samStatMappingFolders, outputFolderBasenameNames)]


bamFilesMAPQFiltering = ["{pathway}/{sample}_filtered.bam".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        MAPQFolders, outputFolderBasenameNames)]


samStatReportFilesMAPQFiltering = ["{pathway}/{sample}.samStatsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        samStatMAPQFolders, outputFolderBasenameNames)]


samFlagReportFilesMAPQFiltering = ["{pathway}/{sample}.samFlagsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        samStatMAPQFolders, outputFolderBasenameNames)]


bamFilesPCRDuplicatesFiltered = ["{pathway}/{sample}_filtered_nodup.bam".format(
    pathway=pathway, sample=sample) for pathway, sample in zip(
        PCRDuplicatesRemovedFolders, outputFolderBasenameNames)]


conditionSortedbamFilesPCRDuplicatesFiltered = fileManagement.sortingbyconditions(
    ctrlcondition=DatasetCtrlAbrevInFile,
    files=bamFilesPCRDuplicatesFiltered)


samStatReportFilesPCRDuplicatesRemoved = ["{pathway}/{sample}.samStatsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        samStatsPCRDuplicatesRemoveFolders, outputFolderBasenameNames)]


samFlagReportFilesPCRDuplicatesRemoved = ["{pathway}/{sample}.samFlagsReport".format(
    pathway = pathway, sample=sample) for pathway, sample in zip(
        samStatsPCRDuplicatesRemoveFolders, outputFolderBasenameNames)]


bigWigFiles = ["{pathway}/{sample}_filtered_nodup.bw".format(
    pathway=pathway, sample=sample) for pathway, sample in zip(
        bigWigFolders, outputFolderBasenameNames)]


mergedBamFiles = ['{bamFilesFolder}/{dataset}_{dataType}.bam'.format(
    bamFilesFolder=bamFilesFolder, dataset=DATASET, dataType=dataType) for bamFilesFolder, dataType in zip(
        bamFilesMergedFolders, DATATYPE)]


indexMergedBamFiles = ['{bamFilesFolder}/{dataset}_{dataType}.bam.bai'.format(
    bamFilesFolder=bamFilesFolder, dataset=DATASET, dataType=dataType) for bamFilesFolder, dataType in zip(
        bamFilesMergedFolders, DATATYPE)]


mergedBigWigFiles = ['{bigWigFolder}/{dataset}_{dataType}.bw'.format(
    bigWigFolder=bigWigFolder, dataset=DATASET, dataType=dataType) for bigWigFolder, dataType in zip(
        BigWigMergeFolders, DATATYPE)]


strandnessMetricsFiles = [
    "{QualControlFolder}/{sample}_strandnessMetrics.txt".format(
        QualControlFolder=iteratorQualityControlFolder, sample=sample) for 
        iteratorQualityControlFolder, sample  in zip(QualControlFolder, outputFolderBasenameNames) 
]

checkCoverageMetricsFiles = [
    "{QualControlFolder}/{sample}_CheckCoverageMetrics.txt".format(
        QualControlFolder=iteratorQualityControlFolder, sample=sample) for 
        iteratorQualityControlFolder, sample  in zip(QualControlFolder, outputFolderBasenameNames) ]

mappingCoverageMetricsFiles = [
    "{QualControlFolder}/{sample}_mappingCoverageMetrics.txt".format(
        QualControlFolder=iteratorQualityControlFolder, sample=sample) for 
        iteratorQualityControlFolder, sample  in zip(QualControlFolder, outputFolderBasenameNames)
]

genesDistribMetricsFiles = [
    "{QualControlFolder}/{sample}_genesDistributionMetrics.txt".format(
        QualControlFolder=iteratorQualityControlFolder, sample=sample) for 
        iteratorQualityControlFolder, sample  in zip(QualControlFolder, outputFolderBasenameNames)
]



bigWigOfConditionComparison = '{bigWigComapreFolder}/{dataset}_Cond_comparison.bw'.format(
    bigWigComapreFolder=BigWigComapreFolder, dataset=DATASET)


multiBamSummary="{multiBamSummFolder}/multiBamSummary.npz".format(multiBamSummFolder=multiBamSummaryFolder)

correlationBamPlot="{correlPlotFolder}/heatmap_SpearmanCorr_readCounts.png".format(
    correlPlotFolder=correlationBamPlotFolder)

correlationBamMatrix="{correlPlotFolder}/heatmap_SpearmanCorr_readCounts.tab".format(
    correlPlotFolder=correlationBamPlotFolder)


# Checking if pipeline is run on one or two datasets

if len(mergedBigWigFiles) < 2:
    singleDataset = True

else:
    singleDataset = False


# Appending the necessary output for all the conditions and datatype in a list

outputListRule = [HTMLReportFASTQCBefTrimming, FASTQsamplesAfterTrimming, 
    samFilesMapping, samStatReportFilesMapping, 
    bamFilesMAPQFiltering, samStatReportFilesMAPQFiltering, 
    samFlagReportFilesMAPQFiltering, bamFilesPCRDuplicatesFiltered, 
    samStatReportFilesPCRDuplicatesRemoved, samFlagReportFilesPCRDuplicatesRemoved, 
    bigWigFiles, mergedBamFiles, indexMergedBamFiles, mergedBigWigFiles, 
    strandnessMetricsFiles, checkCoverageMetricsFiles, 
    mappingCoverageMetricsFiles, genesDistribMetricsFiles,
    bigWigOfConditionComparison, multiBamSummary,
    correlationBamPlot, correlationBamMatrix]






    
summaryResultsPlotFingerprintsFile = "{pathway}/rawCounts.tab".format(pathway=fingerprintsPlotsFolders)
    
plotFingerPrintFigure = "{pathway}/plotFingerPrint.png".format(pathway=fingerprintsPlotsFolders)
    
strandCorrelationOutputFiles = ["{pathway}/{sample}.spp.out".format(pathway=pathway, sample=sample)
    for pathway, sample in zip(StrandCorrelationFolders, outputFolderBasenameNames)]

strandCorrelationsOutputFigures = ["{pathway}/{sample}_filtered_nodup_SPPPlot.pdf".format(
    pathway=pathway, sample=sample) for pathway, sample in zip(
        StrandCorrelationFolders, outputFolderBasenameNames)] 

peaksCallingOutputFiles = ['{pathway}/NA_peaks.narrowPeak'.format(pathway=pathway)
    for pathway in PeaksCallingFolders]

#peaksSAFFileFormat = "{pathway}/peaks.saf".format(pathway=SafFolder)

#FRIPOutputFiles = ["{pathway}/readsInPeaks.txt".format(pathway=pathway)
#    for pathway in FripFolders]

    
outputListRule.append(summaryResultsPlotFingerprintsFile)
outputListRule.append(plotFingerPrintFigure)
outputListRule.append(strandCorrelationOutputFiles)
outputListRule.append(strandCorrelationsOutputFigures)
outputListRule.append(peaksCallingOutputFiles)
#outputListRule.append(peaksSAFFileFormat)
#outputListRule.append(FRIPOutputFiles)

    

outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])

outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])
        
outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_profile.png'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])
        
outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_matrix.png'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])





# Beginning of the workflow

rule all:
    input:
        outputListRule







# Performing FastQC before trimming

rule fastQCBeforeTrim:
    input:
       ["{pathway}/{files}.fastq.gz".format(pathway=pathway, files=files)\
        for pathway, files in zip(FASTQSAMPLESFOLDERS, SAMPLESFILES)]

    output:
        htmlFASTAQC=HTMLReportFASTQCBefTrimming, 
        zipFASTAQC=["{pathway}/{sample}_fastqc.zip".format(pathway=pathway, sample=sample)\
        for pathway, sample in zip(FASTQCFolders, SAMPLESFILES)]


    threads: threadsNumber

    conda: condaEnvironment

    params: 
        outputFolders=FASTQCFolders,
        cpusPerTasks=cpusPerTasks,

    script:
        scriptPath + "/FASTQC.py"









# Performing the trimming 

rule TrimGalore:
    input:
        rules.fastQCBeforeTrim.input
    
    output:
        FASTQsamplesAfterTrimming
        

    conda: condaEnvironment

    params: 
        outputFolders=TrimGalorePaths,
        cpusPerTasks=cpusPerTasks,

    threads: threadsNumber

    script: 
        scriptPath + "/TrimGalore.py"







# Performing the mapping 

rule MappingReadsOnGenome:
    input:
        FoldersTrimmedFastQ=TrimGalorePaths, 
        TrimmedFasta=rules.TrimGalore.output

    output:
       samFilesMapping
    
    params: 
        referenceGenome=referenceGenome, 
        genomeIndexFolder=genomeIndexFolder, 
        organism=organism,
        cpusPerTasks=cpusPerTasks,

    conda: condaEnvironment

    threads: threadsNumber

    script: 
        scriptPath + "/Mapping.py"







# Computing a 'Mapping Report'

rule samStatMapping:
    input:
        rules.MappingReadsOnGenome.output
    
    output:
        SamStatsReports=samStatReportFilesMapping,
        SamFlagsReports=samFlagReportFilesMapping
        

    params:
        plotFolder=samStatMappingFolders 

    conda: condaEnvironment

    threads: threadsNumber

    script: 
        scriptPath + '/SamStats.py'






# Removing the reads with a poor MappingQuality


rule MAPQ:
    input:
        rules.MappingReadsOnGenome.output

    output:
        bamFilesMAPQFiltering
    
    conda: condaEnvironment

    threads: threadsNumber

    params: 
        referenceGenome=referenceGenome,
        cpusPerTasks=cpusPerTasks,

    script: 
        scriptPath + "/FilteringMappingQuality.py"







# Generating a report relative to the reads trimmed by Mapping Quality

rule samStatMAPQ:
    input:
        rules.MAPQ.output
    
    output:
        SamStatsReports=samStatReportFilesMAPQFiltering,
        SamFlagsReports=samFlagReportFilesMAPQFiltering
        

    params:
        plotFolder=samStatMAPQFolders 

    conda: condaEnvironment

    threads: threadsNumber

    script: 
        scriptPath + '/SamStats.py'




# Deleting PCR duplicates 

rule removePCRDuplicates:
    input:
        rules.MAPQ.output
    
    output: 
        bamFiles=bamFilesPCRDuplicatesFiltered, 
        
        indexedBamFiles=["{pathway}/{sample}_filtered_nodup.bam.bai".format(pathway=pathway, sample=sample) 
            for pathway, sample in zip(PCRDuplicatesRemovedFolders, outputFolderBasenameNames)], 
        
        metricsFiles=["{pathway}/{sample}_filtered_nodup_metrics.txt".format(pathway=pathway, sample=sample) 
            for pathway, sample in zip(PCRDuplicatesRemovedFolders, outputFolderBasenameNames)]

    conda: condaEnvironment

    threads: threadsNumber

    script: 
        scriptPath +  "/MarkDuplicates.py"








# Report concerning the PCR duplicates removing 

rule samStatPCRDuplicates:
    input:
        rules.removePCRDuplicates.output
    
    output:
        SamStatsReports=samStatReportFilesPCRDuplicatesRemoved,
        SamFlagsReports=samFlagReportFilesPCRDuplicatesRemoved
        

    params:
        plotFolder=samStatsPCRDuplicatesRemoveFolders 

    conda: condaEnvironment

    threads: threadsNumber

    script: 
        scriptPath + '/SamStats.py'




# Quality Control of the reads strandness 

rule QualControl:
    input:
        rules.removePCRDuplicates.output.bamFiles
    
    output: 
        strandnessOutputFiles = strandnessMetricsFiles,
        checkCoverageOutputFiles = checkCoverageMetricsFiles,
        mappingCoverageOutputFiles = mappingCoverageMetricsFiles,
        genesDistribOutputFiles = genesDistribMetricsFiles,

    conda: condaEnvironment

    threads: threadsNumber

    params:
        bedGenesFiles = bedGenesFiles,
        cpusPerTasks=cpusPerTasks,

    script: 
        scriptPath + "/QualCheck.py"





# Computing bigWig files

rule bamCoverage:
    input:
        rules.removePCRDuplicates.output.bamFiles
    
    output:
        bigWigFiles

    conda: condaEnvironment

    params: 
        referenceGenome=referenceGenome,
        cpusPerTasks=cpusPerTasks,

    threads: threadsNumber

    script: 
        scriptPath + "/bigWigComputation.py"





# Merging Bigwig and comparing them from bam files

if singleDataset:
    rule bigWigMerge:
        input:
            CtrlBamFiles = conditionSortedbamFilesPCRDuplicatesFiltered[0]

        output: 
            bamFilesMerged=mergedBamFiles, 
            bamFilesIndexMerged=indexMergedBamFiles, 
            bigWigMergedFiles=mergedBigWigFiles, 
            bigWigComapreFile=bigWigOfConditionComparison

        conda: condaEnvironment

        params: 
            referenceGenome=referenceGenome,
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset

        script: 
            scriptPath + "/MergeBigWig.py"
else:
    rule bigWigMerge:
        input:
            CtrlBamFiles = conditionSortedbamFilesPCRDuplicatesFiltered[0], 
            TreatBamFiles = conditionSortedbamFilesPCRDuplicatesFiltered[1]

        output: 
            bamFilesMerged=mergedBamFiles, 
            bamFilesIndexMerged=indexMergedBamFiles, 
            bigWigMergedFiles=mergedBigWigFiles, 
            bigWigComapreFile=bigWigOfConditionComparison

        conda: condaEnvironment

        params: 
            referenceGenome=referenceGenome,
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset

        script: 
            scriptPath + "/MergeBigWig.py"





# Computing a correlation plot between samples 

rule correlationBamPlot:
    input:
        rules.removePCRDuplicates.output.bamFiles
    output:
        multiBamSummary=multiBamSummary, 
        correlationPlot=correlationBamPlot,
        correlationMatrix=correlationBamMatrix

    params: 
        sampleNames = outputFolderBasenameNames

    conda: condaEnvironment

    script: scriptPath + "/CorrelationBamPlot.py"




# Computing Lorenz curves for quality control 

if singleDataset:
    
    rule plotFingerPrint:
        input:
            datasetFilesCtrl = fileManagement.sortingbyconditions(ctrlcondition=DatasetCtrlAbrevInFile, 
                files=rules.removePCRDuplicates.output.bamFiles)[0]
        
        output:
            plotFingerprintPicture=plotFingerPrintFigure, 
            plotFingerprintRawCounts=summaryResultsPlotFingerprintsFile
    
        params:
            InputFilesCtrl = "False", 
            InputFilesTreat = "False",
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,


        conda: condaEnvironment

        threads: threadsNumber

        script: scriptPath + '/plotFingerPrint.py'


else:
    rule plotFingerPrint:
        input:
            datasetFilesCtrl = fileManagement.sortingbyconditions(ctrlcondition=DatasetCtrlAbrevInFile, 
                files=rules.removePCRDuplicates.output.bamFiles)[0], 
            
            datasetFilesTreat = fileManagement.sortingbyconditions(ctrlcondition=DatasetCtrlAbrevInFile, 
                files=rules.removePCRDuplicates.output.bamFiles)[1]
        
        output:
            plotFingerprintPicture=plotFingerPrintFigure, 
            plotFingerprintRawCounts=summaryResultsPlotFingerprintsFile
    
        params:
            InputFilesCtrl = "False", 
            InputFilesTreat = "False",
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,


        conda: condaEnvironment

        threads: threadsNumber

        script: scriptPath + '/plotFingerPrint.py'




    


# Computing Strand cross-correlation plots

rule SPP:
    input:
        rules.removePCRDuplicates.output.bamFiles

    output:
        phantomPeaksPictures=strandCorrelationsOutputFigures, 
        phantomPeaksResults=strandCorrelationOutputFiles

    conda: condaEnvironment

    threads: threadsNumber

    params: CondaEnvPathName=CondaEnvPathName

    script: 
        scriptPath + "/phantompeaks.py"




# Computing the coverage matrix to prepare data for 
# heatmap and coverage analysis

if not singleDataset:
    rule coveraGeMatrix:
        input:
            datasetFilesCtrl = rules.bigWigMerge.output.bigWigMergedFiles[0], 
            datasetFilesTreat = rules.bigWigMerge.output.bigWigMergedFiles[1], 
            bedFiles=bedGenesFiles
        
        output:
            gzipMatrixFile = ['{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)], 
            
            heatmapMatrixFile = ['{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)]
        

        conda:condaEnvironment

        threads: threadsNumber

        script:'lib/scripts/ComputeCoverageMatrix.py'


else:
    rule coveraGeMatrix:
        input:
            datasetFilesCtrl = rules.bigWigMerge.output.bigWigMergedFiles[0],
            bedFiles=bedGenesFiles
        
        output:
            gzipMatrixFile = ['{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)], 
            
            heatmapMatrixFile = ['{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)]

        params: 
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,
            typeheatmap=typeheatmap        

        conda:condaEnvironment

        threads: threadsNumber

        script:'lib/scripts/ComputeCoverageMatrix.py'


   


# Computing the profile plot around the TSS
    
rule profilePlotTSS:
    input:
        rules.coveraGeMatrix.output

    output:
        ['{coverageMatrix}/{datasetType}_around_TSS_profile.png'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
            for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)]

    conda: condaEnvironment

    params:
        cpusPerTasks=cpusPerTasks,
        singleDataset=singleDataset,
        typeheatmap=typeheatmap

    script: 'lib/scripts/ComputeProfileAroundTSS.py'
    


# Computing the heatmap plot around the TSS

rule heatmapPlotTSS:
    input:
        rules.coveraGeMatrix.output
        
    output:
        ['{coverageMatrix}/{datasetType}_around_TSS_matrix.png'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
            for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)]

    params:
        cpusPerTasks=cpusPerTasks,
        singleDataset=singleDataset,
        typeheatmap=typeheatmap

    conda: condaEnvironment

    script: 'lib/scripts/ComputeHeatmapAroundTSS.py'



# Peaks calling 

if singleDataset:
    rule PeaksCalling:
        input:
            datasetFiles = rules.removePCRDuplicates.output.bamFiles,
            datasetFilesCtrl = rules.plotFingerPrint.input.datasetFilesCtrl,
            datasetFilesTreat = rules.plotFingerPrint.input.datasetFilesTreat
        
        output: peaksCallingOutputFiles
        
        conda: condaEnvironment

        threads: threadsNumber

        params: 
            peaksCallingType = peaksCallingType, 
            outDirs = PeaksCallingFolders,
            CtrlCondition = DatasetCtrlAbrevInFile, 
            AssembledFilesPeaksCalling = AssembledFilesPeaksCalling,
            cpusPerTasks=cpusPerTasks,
            organism=organism,

        script:
            scriptPath + '/MACS2.py'


else:
    rule PeaksCalling:
        input:
            datasetFiles = rules.removePCRDuplicates.output.bamFiles,
            datasetFilesCtrl = rules.plotFingerPrint.input.datasetFilesCtrl,
            datasetFilesTreat = rules.plotFingerPrint.input.datasetFilesTreat
        
        output: peaksCallingOutputFiles
        
        conda: condaEnvironment

        threads: threadsNumber

        params: 
            peaksCallingType = peaksCallingType, 
            outDirs = PeaksCallingFolders,
            CtrlCondition = DatasetCtrlAbrevInFile, 
            AssembledFilesPeaksCalling = AssembledFilesPeaksCalling,
            cpusPerTasks=cpusPerTasks,
            organism=organism,

        script:
            scriptPath + '/MACS2.py'




    


    

# Convert bed files to saf files

#rule convertBedToSaf:
#    input:
#        rules.cleaningBEDFile.output
        
#    output:
#        peaksSAFFileFormat

#    script:
#        scriptPath + '/convertBedToSaf.py'

    


# Computing FRIP score

#rule FripScoreComputing:
#    input: 
#        bamFiles = rules.removePCRDuplicates.output.bamFiles, 
#        safFiles = rules.convertBedToSaf.output
        
#    output:
#        FRIPOutputFiles

#    conda: condaEnvironment

#    threads: threadsNumber

#    script: 
#        scriptPath + "/FripScore.py"

    

    


