# Loading Librairies

import sys
import subprocess
from snakemake.utils import min_version
import os


from lib.scripts.FileManagement import FileManagement


# Workflow works only from Snkamake 6.0 version

min_version("6.0")


# Defining variables to use in the workflow

DATASET = "" # (data/RNA-Seq)/"foldername"
DATATYPE = ["", ""] # (data/RNA-Seq)/foldername/"Condition1", "Condition2"
DatasetCtrlAbrevInFile = "MCtrl"
threadsNumber = workflow.cores
OSComputer = "Linux"
condaEnvironment = "RNASeqAnalysisForServer.yml"
referenceGenome = (
    "../../data/RNA-Seq/GenomeFasta/mm10/GRCm38.primary_assembly.genome.fa"
)
referenceGTF = "../../data/RNA-Seq/GTFFiles/gencode.vM10.annotation.gtf"
bedGenesFiles = "../../data/RNA-Seq/BEDFile/Mus_musculus.GRCm38.100.bed"
PairedEnd = True
scriptPath = "lib/scripts"
typeheatmap = "TSS"
readsstrandness = "bothsense"
cpusPerTasks = 3

# Computing the FileManagement object to handle with files

fileManagement = FileManagement(
    dataset=DATASET,
    datasetype=DATATYPE,
    inputpath="../../data/RNA-Seq/",
    outputpath="../../output/RNA-Seq/",
    pairedend=PairedEnd,
)


# Getting the path of the Conda environment

CondaEnvPathName = "~/micromamba/envs/ChIPAnalysisMamba"


# Listing all the files and dataset types

SAMPLESFILES = fileManagement.returninglistofsamples()
FASTQSAMPLESFOLDERS = fileManagement.returninputfolders()
OUTPUTFOLDERS = fileManagement.returningoutputfolders()


# For paired end files

pairedEndFoldersBasenames = fileManagement.returnlistofsampleswthoutpe()
OUTPUTFOLDERSPELENGTH = fileManagement.returningpairedendlengthoutputfolders()


# If data are paired end data pairedEndFoldersBasenames is used
# else it is OUTPUTFOLDERS which are used to compute
# destination filenames and foldernames

if PairedEnd:
    outputFolderNames = OUTPUTFOLDERSPELENGTH
    outputFolderBasenameNames = pairedEndFoldersBasenames

else:
    outputFolderNames = OUTPUTFOLDERS
    outputFolderBasenameNames = SAMPLESFILES


# Creating the folders for the main steps of the workflow
# These folders are always created even if the workflow
# is used to process input raw data


FASTQCFolders = [
    f"{pathway}/FastQC/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]


if PairedEnd:
    newFASTQCFolders = []

    for folder in FASTQCFolders:
        newFASTQCFolders.append(folder)
        newFASTQCFolders.append(folder)

    FASTQCFolders = newFASTQCFolders
    del newFASTQCFolders


TrimGalorePaths = [
    f"{pathway}/Trimming/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

MappingFolders = [
    f"{pathway}/Mapping/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

MAPQFolders = [
    f"{pathway}/MAPQ/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

samStatMappingFolders = [
    f"{pathway}/SamStatsMapping/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

samStatMAPQFolders = [
    f"{pathway}/SamStatsMAPQ/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

PCRDuplicatesRemovedFolders = [
    f"{pathway}/NoDup/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

QualControlFolder = [
    f"{pathway}/QualControlMetricsFiles/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

bigWigFolders = [
    f"{pathway}/bigWig/{sample}"
    for pathway, sample in zip(outputFolderNames, outputFolderBasenameNames)
]

BigWigMergeFolders = [
    f"../../output/RNA-Seq/{DATASET}/BigWigMerge/{dataType}"
    for dataType in DATATYPE
]

bamFilesMergedFolders = [
    f"../../output/RNA-Seq/{DATASET}/BamFilesMerged/{dataType}"
    for dataType in DATATYPE
]

# BigWigComapreFolder = '../../output/RNA-Seq/{datasetType}/BigWigCompare'.format(
#    datasetType=DATASET)

multiBamSummaryFolder = f"../../output/RNA-Seq/{DATASET}/MultiBamFolder"

correlationBamPlotFolder = (
    f"../../output/RNA-Seq/{DATASET}/CorrelationBamPlot"
)

CoverageMatrixFolders = [
    f"../../output/RNA-Seq/{DATASET}/CoverageMatrixFiles/{dataType}"
    for dataType in DATATYPE
]


readsCountsFolders = f"../../output/RNA-Seq/{DATASET}/ReadsCounts"

listOfFoldersToCreate = [
    FASTQCFolders,
    TrimGalorePaths,
    MappingFolders,
    MAPQFolders,
    samStatMappingFolders,
    samStatMAPQFolders,
    bigWigFolders,
    BigWigMergeFolders,
    bamFilesMergedFolders,
    QualControlFolder,
    PCRDuplicatesRemovedFolders,
    multiBamSummaryFolder,
    correlationBamPlotFolder,
    CoverageMatrixFolders,
    readsCountsFolders,
]


# Creating selected folders according data

for directory in listOfFoldersToCreate:
    if type(directory) is list:
        for directoryInList in directory:
            shell(f"mkdir -p {directoryInList}")
    else:
        shell(f"mkdir -p {directory}")


# Creating necessary output for the all rule


HTMLReportFASTQCBefTrimming = [
    f"{pathway}/{sample}_fastqc.html"
    for pathway, sample in zip(FASTQCFolders, SAMPLESFILES)
]


FASTQsamplesAfterTrimming = [
    f"{samples}"
    for samples in fileManagement.returningtrimmingsamples()
]

UncompressedFASTQsamplesAfterTrimming = [
    f"{samples}"
    for samples in fileManagement.returningtrimmingsamples(uncompressed=True)
]


samFilesMapping = [
    f"{pathway}/{sample}.samAligned.out.sam"
    for pathway, sample in zip(MappingFolders, outputFolderBasenameNames)
]


samStatReportFilesMapping = [
    f"{pathway}/{sample}.samStatsReport"
    for pathway, sample in zip(samStatMappingFolders, outputFolderBasenameNames)
]


samFlagReportFilesMapping = [
    f"{pathway}/{sample}.samFlagsReport"
    for pathway, sample in zip(samStatMappingFolders, outputFolderBasenameNames)
]


bamFilesMAPQFiltering = [
    f"{pathway}/{sample}_filtered.bam"
    for pathway, sample in zip(MAPQFolders, outputFolderBasenameNames)
]

conditionSortedbamFilesMAPQFiltered = fileManagement.sortingbyconditions(
    ctrlcondition=DatasetCtrlAbrevInFile,
    files=bamFilesMAPQFiltering)

samStatReportFilesMAPQFiltering = [
    f"{pathway}/{sample}.samStatsReport"
    for pathway, sample in zip(samStatMAPQFolders, outputFolderBasenameNames)
]


samFlagReportFilesMAPQFiltering = [
    f"{pathway}/{sample}.samFlagsReport"
    for pathway, sample in zip(samStatMAPQFolders, outputFolderBasenameNames)
]


metricsFilesPCRDuplicatesFiltered = [
    f"{pathway}/{sample}_filtered_nodup_metrics.txt"
    for pathway, sample in zip(PCRDuplicatesRemovedFolders, outputFolderBasenameNames)
]


markDuplicatesBamFiles = [
    f"{pathway}/{sample}_markDuplicates.bam"
    for pathway, sample in zip(PCRDuplicatesRemovedFolders, outputFolderBasenameNames)
]


indexedBamFiles = (
    [
        f"{pathway}/{sample}_filtered.bam.bai"
        for pathway, sample in zip(MAPQFolders, outputFolderBasenameNames)
    ],
)


bigWigFiles = [
    f"{pathway}/{sample}_filtered.bw"
    for pathway, sample in zip(bigWigFolders, outputFolderBasenameNames)
]


mergedBamFiles = [
    f"{bamFilesFolder}/{DATASET}_{dataType}.bam"
    for bamFilesFolder, dataType in zip(bamFilesMergedFolders, DATATYPE)
]


indexMergedBamFiles = [
    f"{bamFilesFolder}/{DATASET}_{dataType}.bam.bai"
    for bamFilesFolder, dataType in zip(bamFilesMergedFolders, DATATYPE)
]


mergedBigWigFiles = [
    f"{bigWigFolder}/{DATASET}_{dataType}.bw"
    for bigWigFolder, dataType in zip(BigWigMergeFolders, DATATYPE)
]


strandnessMetricsFiles = [
    f"{iteratorQualityControlFolder}/{sample}_strandnessMetrics.txt"
    for iteratorQualityControlFolder, sample in zip(
        QualControlFolder, outputFolderBasenameNames
    )
]

checkCoverageMetricsFiles = [
    f"{iteratorQualityControlFolder}/{sample}_CheckCoverageMetrics.txt"
    for iteratorQualityControlFolder, sample in zip(
        QualControlFolder, outputFolderBasenameNames
    )
]


mappingCoverageMetricsFiles = [
    f"{iteratorQualityControlFolder}/{sample}_mappingCoverageMetrics.txt"
    for iteratorQualityControlFolder, sample in zip(
        QualControlFolder, outputFolderBasenameNames
    )
]

genesDistribMetricsFiles = [
    f"{iteratorQualityControlFolder}/{sample}_genesDistributionMetrics.txt"
    for iteratorQualityControlFolder, sample in zip(
        QualControlFolder, outputFolderBasenameNames
    )
]

multiBamSummary = f"{multiBamSummaryFolder}/multiBamSummary.npz"


correlationBamPlot = f"{correlationBamPlotFolder}/heatmap_SpearmanCorr_readCounts.png"


correlationBamMatrix = f"{correlationBamPlotFolder}/heatmap_SpearmanCorr_readCounts.tab"


readsCountsFiles = [
    f"{readsCountsFolders}/{samples}_counts.txt"
    for samples in outputFolderBasenameNames
]


# Checking if pipeline is run on one or two datasets

if len(mergedBigWigFiles) < 2:
    singleDataset = True

else:
    singleDataset = False


# Appending the necessary output for all the conditions and datatype in a list

outputListRule = [
    HTMLReportFASTQCBefTrimming,
    UncompressedFASTQsamplesAfterTrimming,
    samFilesMapping,
    samStatReportFilesMapping,
    bamFilesMAPQFiltering,
    samStatReportFilesMAPQFiltering,
    samFlagReportFilesMAPQFiltering,
    indexedBamFiles,
    strandnessMetricsFiles,
    checkCoverageMetricsFiles,
    mappingCoverageMetricsFiles,
    genesDistribMetricsFiles,
    metricsFilesPCRDuplicatesFiltered,
    markDuplicatesBamFiles,
    bigWigFiles, mergedBamFiles,
    indexMergedBamFiles,mergedBigWigFiles,
    multiBamSummary, correlationBamPlot,
    correlationBamMatrix,
    readsCountsFiles,
]


outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])

outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])

outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_profile.png'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])

outputListRule.append(['{coverageMatrix}/{datasetType}_around_TSS_matrix.pdf'.format(coverageMatrix=coverageMatrix, datasetType=datasetType)\
    for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)])


# Beginning of the workflow


rule all:
    input:
        outputListRule,


# Performing FastQC before trimming


rule fastQCBeforeTrim:
    input:
        [
            f"{pathway}/{files}.fastq.gz"
            for pathway, files in zip(FASTQSAMPLESFOLDERS, SAMPLESFILES)
        ],
    output:
        htmlFASTAQC=HTMLReportFASTQCBefTrimming,
        zipFASTAQC=[
            f"{pathway}/{sample}_fastqc.zip"
            for pathway, sample in zip(FASTQCFolders, SAMPLESFILES)
        ],
    threads: threadsNumber
    conda:
        condaEnvironment
    params:
        outputFolders=FASTQCFolders,
        cpusPerTasks=cpusPerTasks,
    script:
        f"{scriptPath}/FASTQC.py"


# Performing the trimming


rule TrimGalore:
    input:
        rules.fastQCBeforeTrim.input,
    output:
        UncompressedFASTQsamplesAfterTrimming,
    conda:
        condaEnvironment
    params:
        outputFolders=TrimGalorePaths,
        cpusPerTasks=cpusPerTasks,
    threads: threadsNumber
    script:
        f"{scriptPath}/TrimGalore.py"


# Performing the mapping


rule MappingReadsOnGenome:
    input:
        FoldersTrimmedFastQ=TrimGalorePaths,
        TrimmedFasta=rules.TrimGalore.output,
    output:
        samFilesMapping,
    
    conda: 
        condaEnvironment

    params:
        referenceGenome=referenceGenome,
        referenceGTF=referenceGTF,
        cpusPerTasks=cpusPerTasks,
   
    threads: threadsNumber
    script:
        f"{scriptPath}/Mapping.py"


# Computing a 'Mapping Report'


rule samStatMapping:
    input:
        rules.MappingReadsOnGenome.output,
    output:
        SamStatsReports=samStatReportFilesMapping,
        SamFlagsReports=samFlagReportFilesMapping,
    params:
        plotFolder=samStatMappingFolders,
    conda:
        condaEnvironment
    threads: threadsNumber
    script:
        f"{scriptPath}/SamStats.py"


# Removing the reads with a poor MappingQuality


rule MAPQ:
    input:
        rules.MappingReadsOnGenome.output,
    output:
        bamFilesMAPQFiltering=bamFilesMAPQFiltering,
        indexedBamFiles=indexedBamFiles,
    conda:
        condaEnvironment
    threads: threadsNumber
    params:
        referenceGenome=referenceGenome,
        cpusPerTasks=cpusPerTasks,
    script:
        f"{scriptPath}/FilteringMappingQuality.py"


# Quality Control of the RNA-Seq samples


rule QualControl:
    input:
        rules.MAPQ.output.bamFilesMAPQFiltering,
    output:
        strandnessOutputFiles=strandnessMetricsFiles,
        checkCoverageOutputFiles=checkCoverageMetricsFiles,
        mappingCoverageOutputFiles=mappingCoverageMetricsFiles,
        genesDistribOutputFiles=genesDistribMetricsFiles,
    conda:
        condaEnvironment
    threads: threadsNumber
    params:
        bedGenesFiles=bedGenesFiles,
        cpusPerTasks=cpusPerTasks,
    script:
        f"{scriptPath}/QualCheck.py"


# Generating a report relative to the reads trimmed by Mapping Quality


rule samStatMAPQ:
    input:
        rules.MAPQ.output.bamFilesMAPQFiltering,
    output:
        SamStatsReports=samStatReportFilesMAPQFiltering,
        SamFlagsReports=samFlagReportFilesMAPQFiltering,
    params:
        plotFolder=samStatMAPQFolders,
    conda:
        condaEnvironment
    threads: threadsNumber
    script:
        f"{scriptPath}/SamStats.py"


# Marking PCR duplicates


rule MarkPCRDuplicates:
    input:
        rules.MAPQ.output,
    output:
        metricsFiles=metricsFilesPCRDuplicatesFiltered,
        markedBamFiles=markDuplicatesBamFiles,
    conda:
        condaEnvironment
    threads: threadsNumber
    script:
        f"{scriptPath}/MarkDuplicates.py"


# Computing bigWig files


rule bamCoverage:
    input:
        rules.MAPQ.output.bamFilesMAPQFiltering,
    output:
        bigWigFiles,
    conda:
        condaEnvironment
    params:
        referenceGenome=referenceGenome,
        cpusPerTasks=cpusPerTasks,
    threads: threadsNumber
    script:
        f"{scriptPath}/bigWigComputation.py"


# Merging Bigwig and comparing them from bam files



if singleDataset:
    rule bigWigMerge:
        input:
            bamFilescontrol=conditionSortedbamFilesMAPQFiltered[0]
        output:
            bamFilesMerged=mergedBamFiles,
            bamFilesIndexMerged=indexMergedBamFiles,
            bigWigMergedFiles=mergedBigWigFiles,
        conda:
            condaEnvironment
        params:
            referenceGenome=referenceGenome,
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,
        script:
            f"{scriptPath}/MergeBigWig.py"

else:
    rule bigWigMerge:
        input:
            bamFilescontrol=conditionSortedbamFilesMAPQFiltered[0],
            bamFilestreated=conditionSortedbamFilesMAPQFiltered[1],
        output:
            bamFilesMerged=mergedBamFiles,
            bamFilesIndexMerged=indexMergedBamFiles,
            bigWigMergedFiles=mergedBigWigFiles,
        conda:
            condaEnvironment
        params:
            referenceGenome=referenceGenome,
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,
        script:
            f"{scriptPath}/MergeBigWig.py"





# Computing a correlation plot between samples


rule correlationBamPlot:
    input:
        rules.MAPQ.output.bamFilesMAPQFiltering,
    output:
        multiBamSummary=multiBamSummary,
        correlationPlot=correlationBamPlot,
        correlationMatrix=correlationBamMatrix,
    params:
        sampleNames=outputFolderBasenameNames,
    conda:
        condaEnvironment
    script:
        f"{scriptPath}/CorrelationBamPlot.py"


# Computing the coverage matrix to prepare data for
# heatmap and coverage analysis

if not singleDataset:
    rule coveraGeMatrix:
        input:
            ctrldatasetFiles=rules.bigWigMerge.output.bigWigMergedFiles[0],
            treateddatasetFiles=rules.bigWigMerge.output.bigWigMergedFiles[1],
            bedFiles=bedGenesFiles,
        output:
            gzipMatrixFile=[
                f"{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz"
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
            ],
            heatmapMatrixFile=[
                f"{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile"
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
            ],
        conda:
            condaEnvironment
        params:
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,
            typeheatmap=typeheatmap
        threads: threadsNumber
        script:
            f"{scriptPath}/ComputeCoverageMatrix.py"

else:
    rule coveraGeMatrix:
        input:
            ctrldatasetFiles=rules.bigWigMerge.output.bigWigMergedFiles[0],
            bedFiles=bedGenesFiles,
        output:
            gzipMatrixFile=[
                f"{coverageMatrix}/{datasetType}_around_TSS_matrixFile.gz"
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
            ],
            heatmapMatrixFile=[
                f"{coverageMatrix}/{datasetType}_around_TSS_HeatmapMatrixFile"
                for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
            ],
        conda:
            condaEnvironment
        params:
            cpusPerTasks=cpusPerTasks,
            singleDataset=singleDataset,
            typeheatmap=typeheatmap
        threads: threadsNumber
        script:
            f"{scriptPath}/ComputeCoverageMatrix.py"



# Computing the profile plot around the TSS


rule profilePlotTSS:
    input:
        rules.coveraGeMatrix.output.gzipMatrixFile,
    output:
        [
            f"{coverageMatrix}/{datasetType}_around_TSS_profile.png"
            for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
        ],
    conda:
        condaEnvironment
    params: 
        cpusPerTasks=cpusPerTasks,
        singleDataset=singleDataset,
        typeheatmap=typeheatmap
    script:
        f"{scriptPath}/ComputeProfileAroundTSS.py"


# Computing the heatmap plot around the TSS


rule heatmapPlotTSS:
    input:
        rules.coveraGeMatrix.output.gzipMatrixFile,
    output:
        [
            f"{coverageMatrix}/{datasetType}_around_TSS_matrix.pdf"
            for coverageMatrix, datasetType in zip(CoverageMatrixFolders, DATATYPE)
        ],
    conda:
        condaEnvironment
    params:
        cpusPerTasks=cpusPerTasks,
        singleDataset=singleDataset,
        typeheatmap=typeheatmap
    script:
        f"{scriptPath}/ComputeHeatmapAroundTSS.py"


# Counting the number of genes


rule countingGenes:
    input:
        rules.MAPQ.output.bamFilesMAPQFiltering,
    output:
        readsCountsFiles=readsCountsFiles,
    params:
        referenceGTF=referenceGTF,
        readsstrandness=readsstrandness
    conda:
        condaEnvironment
    script:
        f"{scriptPath}/CountingGenes.py"
