#!/usr/bin/env python3

# -*- coding:utf-8 -*-

"""convertBedtoSaf.py
Author: Hugo N.G.Martin

This module allows from the Snakemake workflow to convert the input bed files 
generated by MACS2 for each sample in a SAF file format compatible with the 
command "featureCounts" to counts the reads under the peaks for each sample.

All the parameters are given by the Snakefile when the workflow is running. 

This module should be run exclusively by the Snakemake workflow

The activation of the mamba environment "ChIPAnalysisMamba" is required to
launch this module

This file contains the following functions:
    * convertbedtosaf - Take the input samples bed files to convert them in a SAF file format
"""

# Loading librairies

from concurrent.futures import ThreadPoolExecutor


# Creating the pool for multithreading

pool = ThreadPoolExecutor(max_workers=snakemake.threads)


def convertbedtosaf(bedfile, outputsafile):
    """
    Take the input samples bed files to convert them in a SAF file format

    Parameters
    ----------
    bedfile : str
        The file location to the bed file generated by MACS2
    outputsafile : str
        The file location to the output file in a SAF format
    
    Returns
    -------
    None
    """

    # Opening the bed file and reformating

    with open(bedfile, 'r', encoding="utf-8") as bedfileinstance:

        for linebed in bedfileinstance:

            linebed = linebed.replace('\n', '')
            linesplitted = linebed.split('\t')
            newline = '\t'.join([linesplitted[0] + '.' + linesplitted[1] +
                '.' + linesplitted[2], linesplitted[0], linesplitted[1],
                linesplitted[2], linesplitted[5]])

            # Writting the new line in the new file

            with open(f'{outputsafile}', 'a', encoding="utf-8") as saffile:
                saffile.write(newline + '\n')

    saffile.close()


# Transforming all the bed files in SAF files

for bedFiles, outputSafFile in zip(snakemake.input, snakemake.output):

    pool.submit(convertbedtosaf, bedFiles, outputSafFile)

pool.shutdown(wait=True)
