#!/usr/bin/python3

# -*- coding:utf-8 -*-

"""CorrelationBamPlot.py
Author: Hugo N.G.Martin

This module allows from the Snakemake workflow to compute a spearman correlation heatmap
with the command "plotCorrelation" from input bam files generated by Samtools and Bowtie2. 

All the parameters are given by the Snakefile when the workflow is running. 

This module should be run exclusively by the Snakemake workflow

The activation of the mamba environment "ATACAnalysisMamba" is required to
launch this module
"""

# Importing librairies

from snakemake import shell

# Reformating the list of bam files and folder names in two strings spaced by a space charachter

LISTOFBAMSAMPLESREFORMATED = ' '.join(snakemake.input)
LISTOFFOLDERNAMESREFORMATED = ' '.join(snakemake.params.sampleNames)

# Computing the multiBamSummary

threads = snakemake.threads

shell(f"multiBamSummary bins -p {threads} --bamfiles {LISTOFBAMSAMPLESREFORMATED} --labels {LISTOFFOLDERNAMESREFORMATED} -o {snakemake.output.multiBamSummary}")

# Computing the correlation plot

shell(f"plotCorrelation -in {snakemake.output.multiBamSummary} --corMethod spearman --skipZeros --plotTitle\
    'Spearman Correlation of Read Counts' --whatToPlot heatmap --colorMap RdYlBu --plotNumbers\
        -o {snakemake.output.correlationPlot} --outFileCorMatrix {snakemake.output.correlationMatrix}")
