#!/usr/bin/env python3

# -*- coding:utf-8 -*-

"""FilteringMappingQuality.py
Author: Hugo N.G.Martin

This module allows from the Snakemake workflow to filter the Mapping quality from 
the sam files generated by Bowtie2 with "samtools view". 

All the parameters are given by the Snakefile 
when the workflow is running. 

This module should be run exclusively by the Snakemake workflow

The activation of the mamba environment "ATACAnalysisMamba" is required to
launch this module

This file contains the following function:
    * filteringpoormapq - Take the input SAM file, filter the mapping quality and sort the output BAM file 
"""


# Importing librairies

from concurrent.futures import ThreadPoolExecutor
from snakemake import shell


# Creating the pool for multithreading

threadsNumb = int(snakemake.threads / snakemake.params.cpusPerTasks)
pool = ThreadPoolExecutor(max_workers=threadsNumb)



def filteringpoormapq(samfile, outputfile):
    """
    Take the input SAM file, filter the mapping quality and sort the output BAM file 

    Parameters
    ----------
    samfile : str
        Pathname to the input SAM file to filter
    outputfile : str
        Pathname to the filtered output BAM file
    Returns
    -------
    None
    """

    threads = snakemake.params.cpusPerTasks
    referencegenome = snakemake.params.referenceGenome

    shell(f"samtools view --threads {threads} -S {samfile} -T {referencegenome} -q 30 -f2 -b | samtools sort - -o {outputfile}")


# Iterating all the files in the folders to make the mapping against the reference genome

for inputFile, outputFile in zip(snakemake.input, snakemake.output):

    # Filtering reads with poor mapping quality

    pool.submit(filteringpoormapq, inputFile, outputFile)



pool.shutdown(wait=True)

